pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'mvn -B -DskipTests -Denforcer.skip=true clean package'
      }
    }

    stage('Test') {
      steps {
        sh 'mvn -Denforcer.skip=true test'
      }
      post {
        always { junit 'target/surefire-reports/*.xml' }
      }
    }

    stage('Deliver') {
      steps {
        sh '''
          set -eux
          mvn -B -DskipTests -Denforcer.skip=true package

          echo "Contents of target/:"
          ls -la target

          JAR=$(ls -1 target/*.jar | head -n1)
          echo "Running $JAR"
          java -jar "$JAR"
        '''
      }
    }
  
  }
}
